import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalState from "@/context";
import { Provider } from "./provider";
import NavBar from "@/components/NavBar";
import { navElement } from "@/data";
import XNavBar from "@/components/XNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <NavBar navElement={navElement} />
          <div className="md:hidden">
            <XNavBar />
          </div>
          <GlobalState>{children}</GlobalState>
        </body>
      </Provider>
    </html>
  );
}
